name: 'MovieButAds > Yifan'
version: '0.1.0'
namespace: 'https://yifan.movie-but-ads.mutoo.im'
icon: 'https://www.google.com/s2/favicons?domain=www.yifan.tv'
match:
  - 'https://www.yifan.tv/*'
  - 'https://www.yfsp.tv/*'
  - 'https://www.yfsp.me/*'
  - 'https://www.ayf.tv/*'
  - 'https://www.aiyifan.tv/*'
  - 'https://www.wyav.tv/*'
  - 'https://www.flyv.tv/*'
  - 'https://www.jssp.tv/*'
  - 'https://www.iyf.tv/*'
  - 'https://www.lgsp.tv/*'
  - 'https://www.hlive.io/*'
